services:
  solr:
    image: solr:9.7.0
    ports:
       - "8983:8983"
    volumes:
      - ./solr:/var/solr
    command:
      - solr-precreate
      - papayaregistry
    networks:
      - papaya-registry-net
networks:
  papaya-registry-net: