spring:
  application:
    name: papaya-client
  datasource:
    url: jdbc:derby:db;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
papaya:
  port: 3390
  workspace: /home/tronxi/papaya
  tracker: https://tronxi.ddns.net/tracker
logging:
  level:
    root: WARN

