spring:
  application:
    name: papaya-client
  datasource:
    url: jdbc:mysql://localhost:3306/papaya?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: papaya
    password: papayapass
  jpa:
    hibernate:
      ddl-auto: update
papaya:
  port: 3390
  workspace: /home/tronxi/papaya
  tracker: http://192.168.1.17:8079
logging:
  level:
    root: WARN

