server:
  port: 7070
spring:
  application:
    name: papaya-client
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
build:
  version: @project.version@
papaya:
  port: 3390
  tracker: https://tronxi.ddns.net/tracker
  useOnlyLocalAddress: false
logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
    root: WARN

