services:
  redis:
    image: redis:latest
    container_name: redis
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - papaya_tracker_network
    volumes:
      - ./redis:/data
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--requirepass"
      - "${REDIS_PASSWORD}"
  papaya-tracker:
    container_name: papaya-tracker
    image: papaya-tracker:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8079:8079"
    networks:
      - papaya_tracker_network

networks:
  papaya_tracker_network:
